### ISSUE TITLE
spin90 and changing icon

### ISSUE THREAD

**Issue by DATL4G** [Ecodev/fab-speed-dial#24]
Please add spin 90
```css
.spin90 {
    -webkit-transform: rotate(90deg);
    transform: rotate(90deg);
}
```
And please provide a method to specify the icon when it's closed and when its open.

Example:
So when it's closed it shows a **'check'** and when you click on it and open it the icon changes to **'close'**
